name: Image Submission
description: Submit an image.
title: "[Image Submission]: "
body:
  - type: input
    id: username
    attributes:
      label: Geode username
      description: Your Geode username to be associated with the image
      placeholder: ex. Alphalaneous
    validations:
      required: true
  - type: input
    id: image-url
    attributes:
      label: Image URL
      description: The URL to the image you want to be uploaded here.
      placeholder: ex. https://github.com/Alphalaneous/ModDevBranding-Images/blob/main/Images/alphalaneous.png
    validations:
      required: true